- commands/enter.js
- tests/editor.test.js
Note: I notice that it breaks when doing enter then backspace at the end of the <pre>. That is due to a pre-existing bug that puts a <br> at the end of the <pre> when merging an element into it. This should be fixed separately as its scope is definitely larger than just <pre> nodes.
> [ADD] support for enter in <pre>

- src/tests/editor.test.js
- src/tests/fontAwesome.test.js
- src/utils/utils.js
Take some spaces into account and ignore others in the method `isVisibleStr()`
It's necessary to be able to properly delete a space that has been detached from a preceding text node in a previous operation.
ex : `<p>ab[]c <span>de</span></p>`
first delete forward will split the text node in [ab] and[ ]
the second delete forward must not ignore the white space here.
> [FIX] Utils: better visible string detection 

- src/editor.js
- src/tests/editor.test.js
This fixes a bug that triggered an infinite loop when deleting range in `<p>abc[</p><p t="unbreak">d]ef</p>`.
The selection was not properly rolled back when rolling back in the middle of a range deletion process. This was solved by recording the cursor position in the `deleteRange` loop when no error or rollback occurred.
Before this fix, this was the dom at the beginning of each step of the `deleteRange` loop:
```html
1. <p>abc[<img></p><p t="unbreak">d]ef</p>
2. <p>abc<img></p><p t="unbreak">[]ef</p>
3. <p>abc[<img></p><p t="unbreak">e]f</p>
4. <p>ab[]<img></p><p t="unbreak">ef</p>
5. <p>[]<img></p><p t="unbreak">ef</p>
6. []<p><img></p><p t="unbreak">ef</p>
```
After rollback 1, we had dom 2 with the selection of dom 1.
This being corrected, we predictably entered an infinite loop …
> [FIX] prevent infinite loop in deleteRange

- src/editor.js
- src/tests/editor.test.js
- src/tests/utils.js
- Adding a call to `historyStep` at the end of redo ensures we have no inconsistency and our last step is a placeholder.
- Removing the history step that was redone as well as its equivalent undo history step ensures we do not have an infinite redo loop.
> [FIX] properly redo

- src/editor.js
When bolding a selection including a fontawsome, firefox would push the fontawesome to the end of the selection.
> [FIX] fix bold/fontawesome issue on firefox

- src/commands/deleteBackward.js
- src/tests/editor.test.js
- src/utils/utils.js
oDeleteBackward would loop infinitely when trying to delete a range containing a img that was displayed as a block.
> [FIX] fix oDeleteBackward infinite loop

- src/editor.js
When selecting accross nodes, toggle list would reach the `<html>` node, try to get its closest block parent which would be null, then access the tagName of null, which would crash.
Fixed by using `getTraversedNodes` instead of `leftDeepFirstPath` to iterate over the selected nodes.
> [FIX] fix toggle list

- src/utils/utils.js
When divs aren't unbreakable, pressing enter can duplicate elements it shouldn't
eg. when the cursor is at the end of a "big box" type of block in website.
> [FIX] make divs unbreakable

- src/commands/shiftTab.js
Unindent in the case of a nested li would only check that it is the only child of its ul, removing the parent li in that case, whithout checking that the ul was also the only child of the parent li.
Long story short, unindenting this:
```html
<ul>
<li class="oe-nested">
<ul><li>1</li></ul>
<ul><li>[2]</li></ul>
</li>
</ul>
```
would result in this
```html
<ul>
<li>[2]</li>
</ul>
```
Instead of this
```html
<ul>
<li class="oe-nested">
<ul><li>1</li></ul>
</li>
<li>[2]</li>
</ul>
```
> [FIX] fix unindent li behavior

- src/commands/enter.js
Bug report : [SBU] Press "Enter" at the end of the link, the first letter of the new line is within the link...: https://drive.google.com/file/d/1RdNS1oPAUq8n-e82KC2VUUSq95JbjaP0/view
> [FIX] break link after enter if cursor at the end of the <a> tag

- src/commands/enter.js
- src/editor.js
- src/tests/editor.test.js
- src/tests/list.test.js
This addresses the following bug report:
[SBU] Note: Can't get rid of padding in a text.
❗️ Steps to Reproduce :
1. Start note editing
2. Write a word
3. Select the word
4. Change the font-size to 36
5. Press `ENTER`
6. Write another word
7. Press `CTRL+A`, then `BACKSPACE`
8. There is still a strange padding -> NOK ❌
✅ Expected behavior :
> there should be no padding around unformatted text
As it turns out the problem was two-fold:
1. `ENTER` at the end of a `<span>` duplicated the `<span>` into the next line but the browser would write outside of it. Because there was a `font-size` style on the `<span>`, the line was bigger that its text.
2. `BACKSPACE`/`DELETE` on the whole block with the `<span>` would leave the `<span>` empty, making it effectively impossible to get rid of.
This …
> [FIX] prevent empty span on enter/delete

- src/editor.js
Bug report : 
[SGE-03] Website editor : unlink button doesn't work when focus inside a link
👁‍ See: https://www.awesomescreenshot.com/video/2964099?key=b2a21716a0c80749a5f288b45d19038c
❗️ Steps to Reproduce : 
1. start website editing
2. add a snippet text
3. create a link
4. click in the newly created link
5. click the unlink button in the toolbar it doesn't work -> NOK ❌
✅ Expected behavior : 
unlink buton should always unlink the slected range or the link the cursor is anchor into
ℹ️ Branch: master-odoo-editor-integration-all | Last Commit: odoo:9e0f456b [FIX] create link rather than getting it
> [FIX] unlink was broken after be5dd084

- src/editor.js
Prevent this bug in Odoo:
1. Create a mail with template 3
2. Select backwards (with the mouse) from just after the last "Read more" button, until the beginning of "Premium Pass"
3. Press the BACKSPACE key
4. Traceback: "Uncaught TypeError: Cannot read property 'nodeName' of null" at Text.oDeleteBackward > HTMLElement.oDeleteBackward > HTMLElement.oDeleteBackward > moveNodes
> [FIX] prevent traceback on delete

- src/tests/utils.test.js
- src/utils/utils.js
getAdjacent was written with the intent of easyly finding groups of nodes.
For example, a group of nodes that should be wrapped into a <p> but are direct children of the root editable: you would need to grab all the inline and text node that are siblings, but stop collecting them once you encounter a block.
> [ADD] make get adjacent fit current use case

- src/utils/utils.js
Further reading on this issue:
- https://github.com/w3c/csswg-drafts/issues/610
- https://github.com/whatwg/html/pull/2298
- https://stackoverflow.com/a/45143493/4633524
To test the native behavior of `<br>` in and out of a flexbox: https://jsfiddle.net/jko4fh9y/
> [FIX] ensure <br> is never identified as a block

- src/editor.js
when using the regex in a string replace it was replacing all the classes after the color classes as well
> [FIX] color element : fix regex to keep classes after replaced color classes

- src/editor.js
`_insertHTML()` was not returning the value from `_insert()` which is necessary for the table insertion logic to function properly.
> [FIX] table : fix traceback on table insertion

- src/editor.js
In some cases*, pressing "ENTER" quickly triggers an `insertText` input event with `data === null` instead of a `insertParagraphBreak`. This ensures the proper expected behavior instead.
\* In Odoo Website Builder: click in a title selects the whole title. If you then quickly press a letter followed by "ENTER", the aforementioned behavior is triggered.
> [FIX] properly insert paragraph on enter, even on wrong browser event

- src/utils/utils.js
When in an iframe, the node passed to isBlock can be in a different window than `Element` so `node instanceof Element` will always be false.
This prevents an error triggered by this issue.
> [FIX] prevent traceback on isBlock in iframe

- src/editor.js
Will be used in Odoo when scrolling in the main page must change the editor toolbar visual position.
> [IMP] toolbar: add public method to update the toolbar position

- src/editor.js
- src/tests/editor.test.js
- src/utils/utils.js
We achieve this by inserting and selecting a zero-width space when deleting the element.
This is so far limited to unremovable elements but we could potentially expand this logic to all inlines if we choose to have that behavior. In that case though we'd have to handle the systematic removal of these potentially parasitic zero-width spaces, and adapt a lot of tests.
> [IMP] keep cursor in an unremovable inline element after it was emptied

- src/editor.js
In some cryptic cases, inserting a font awesome in text made it so that when selecting the character just after it gave us a deep range that was the text after that font awesome, at offset 0. This is correct, however it had a side effect in `deleteRange` in that it failed to properly set the cursor on correcting trailing spaces. In fact there was no space to preserved but it preserved it nonetheless, and we ended up at the end of the text.
This commit fixes that issue by being a little bit more restrictive in the preservation of space: only do it when absolutely necessary (two adjacent spaces or a trailing space and a merging of blocks).
> [FIX] properly set the cursor after delete next to font awesome

- src/commands.js
- src/editor.js
- src/utils/utils.js
Thus far, the editor only handled text-only pasting/dropping. This commit makes it so that it now handles html pasting/dropping, and ensures that text pasting is properly escaped (to prevent evaluating html strings on paste).
When pasting html, the editor filters the nodes, their attributes and their classes through a combination of a whitelist and a blacklist. Nodes that match blacklisted or non-whitelisted selectors are removed and their contents are unwrapped recursively. Attributes and classes that are blacklisted or non-whitelisted are removed. What is kept are basic styling elements (eg: h1, strong, ...), images (with their src attribute), links (with the href attribute), and a selection of classes the edition of which is supported by the editor.
> [FIX] properly paste/drop escaped text and filtered html

- src/editor.js
- src/utils/utils.js
Clicking in the (non-floating) toolbar, then on one of its buttons would edit the toolbar itself (eg., clicking on a list button would insert a list in the toolbar).
This adds a check on toolbar events so they can only affect what is in the editable area.
> [FIX] prevent editing the toolbar with the toolbar

- src/commands.js
This addresses a bug that occurs when selecting over two paragraphs that are separated by some whitespace. It would create multiple indented lists.
Task: 2567795
> [FIX] properly create multi-paragraph list with whitespace

- src/editor.js
This addresses a bug that occurred is Odoo when outdenting a list: besides outdenting, the 'Tab' keydown also did its default behavior so the cursor ended up in a different field.
Task: 2555704
> [FIX] properly stop 'Tab' keydown event from propagating

- src/commands.js
When inserting HTML, we sometimes need to split blocks to prevent weird nesting of blocks. However, that process has the potential of generating shrunk blocks (blocks without a height), such as `<p></p>`. This prevents it from happening.
> [FIX] prevent shrunk blocks on split during insert html

- src/commands.js
When inserting HTML, we sometimes need to split blocks to prevent weird nesting of blocks. However, that process has the potential of generating shrunk blocks (blocks without a height), such as <p></p>. This prevents it from happening.
> [MERGE] Forward port of 97970d04a74cff1d4a858f01375e62825b673e55 into master

- src/editor.js
Sometimes Google Chrome wrongly triggers an input event with `data`
being `null` on `deleteContentForward` and `insertParagraph`. Luckily
Chrome provides the proper signal with the event `beforeinput`.
A fix had already been made for enter but not for `deleteContentForward`.
> [FIX] deleteContentForward on google chrome

- src/commands.js
When inserting blocks, we often need to split the node in which we're inserting. The code that makes that happen had an issue in its while statement that checked the wrong node, resulting in overreaching splits. This fixes that while statement.
> [FIX] prevent splitting the wrong parent on paste
